In [16]:
import pandas as pd 
import yaml
import sys

users_df = pd.read_csv("../data1/users.csv") 

with open("../data1/books.yaml") as books:
    data=yaml.safe_load(books) 
books_df = pd.DataFrame(data)

orders_df = pd.read_parquet("../data1/orders.parquet")

In [27]:
users_df.head(10)

,id,name,address,phone,email
0,44533,Hoyt Carter,"Apt. 300 8604 Ashlyn Wells, Effertzstad, ID 02997",(462) 385-4294,mckinley.rowe@harber.example
1,46128,Marco Kulas,"Apt. 538 816 Bechtelar Ferry, Lincolnhaven, KS...",913.466.4487,francisco@murray-cronin.test
2,46407,Denny Goyette LLD,"Apt. 174 39450 Mohr Rapids, Port Neomistad, AL...",(801) 970-3335,marguerita@wuckert.test
3,44602,Zackary Heller,"Apt. 608 74228 Bogan Valley, South Stepanieshi...",895.829.5417,annabelle@hessel.test
4,45828,Jess Beier,"2716 Jacobi Path, Ziemanntown, SC 65624-4660",(113) 784-3410,minh@hettinger.example
5,46005,Sen. Luann Borer,"Suite 569 413 Augustus Highway, Lake Harlan, D...",(623) 090-4763,maria@bayer.example
6,45091,Else Watsica,"71804 Kulas Pass, Tulaville, VA 22476-5783",(119) 534-1919,madge@mccullough.example
7,47298,Gladys Stamm Sr.,"Apt. 322 122 Ha Light, Ornchester, IA 60395-9377",889-163-5117,lucio.wiza@hermann.example
8,44757,Pauline Senger,"Apt. 990 28804 Smitham Walks, Byronchester, NY...",360-108-5596,cammie@kling.example
9,47274,Allan Bogisich,"Suite 541 86944 Bennett Squares, West Timmysid...",881 328 9660,janetta_marvin@koelpin.example

In [18]:
users_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3293 entries, 0 to 3292
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3293 non-null   int64
 1   name     3293 non-null   object
 2   address  3177 non-null   object
 3   phone    3293 non-null   object
 4   email    3293 non-null   object
dtypes: int64(1), object(4)
memory usage: 128.8+ KB

In [28]:
books_df.head(10)

,:id,:title,:author,:genre,:publisher,:year
0,19199,The Yellow Meads of Asphodel,Carolyne West,Classic,Mainstream Publishing,2009
1,19398,From Here to Eternity,"Rep. Heath Stiedemann, Gino Welch, Haydee Larson",Short story,Vintage Books,2001
2,19483,Eyeless in Gaza,Vannessa Price,Biography/Autobiography,Pavilion Books,1886
3,19506,Precious Bane,Miss Yong Wyman,Realistic fiction,New English Library,2021
4,19570,City of God,Travis Moore,Suspense/Thriller,Bellevue Literary Press,1847
5,19264,The Way of All Flesh,Matthew Breitenberg,Legend,,1987
6,19210,3 Idiots,Julianne Keeling,Folklore,McFarland & Company,1992
7,19536,Memento,Alina Oberbrunner,Essay,Bowes & Bowes,1982
8,18997,Terrible Swift Sword,Roni Davis,Crime/Detective,Burns & Oates,1983
9,19166,Myst,Laverne Lemke,Legend,Mark Batty Publisher,2002

In [20]:
books_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   :id         753 non-null    int64
 1   :title      753 non-null    object
 2   :author     753 non-null    object
 3   :genre      753 non-null    object
 4   :publisher  751 non-null    object
 5   :year       751 non-null    object
dtypes: int64(1), object(5)
memory usage: 35.4+ KB

In [21]:
orders_df.head()

,id,user_id,book_id,quantity,unit_price,timestamp,shipping
0,71389,47288,18976,2,27.00$,10/01/24 10:38:08 A.M.,None
1,66343,47049,19403,1,€50¢50,10:14;19-Oct-2024,"4940 Arnoldo Keys, West Arnette, KS 77599"
2,72606,46685,19500,1,USD 45.99,"22:13:35,2025-07-02",
3,68462,45336,18992,1,€ 71.00,2025-10-20 16:25:20,
4,72691,45311,19388,1,52.25 $,"08:48:47 A.M.,28-August-2024",None

In [22]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11237 entries, 0 to 11236
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          11237 non-null  int64
 1   user_id     11237 non-null  int64
 2   book_id     11237 non-null  int64
 3   quantity    11237 non-null  int32
 4   unit_price  11237 non-null  object
 5   timestamp   11237 non-null  object
 6   shipping    8427 non-null   object
dtypes: int32(1), int64(3), object(3)
memory usage: 570.8+ KB

In [26]:
orders_df['quantity'].describe()

count    11237.000000
mean         1.524428
std          0.987486
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          5.000000
Name: quantity, dtype: float64