In [2]:
import pandas as pd 
import yaml

users_df = pd.read_csv("../data2/users.csv") 

with open("../data2/books.yaml") as books:
    data=yaml.safe_load(books) 
books_df = pd.DataFrame(data)

orders_df = pd.read_parquet("../data2/orders.parquet")

In [23]:
print("Users df: " + str(users_df.duplicated().sum()))
print("Books df: " + str(books_df.duplicated().sum()))
print("Orders df: " + str(orders_df.duplicated().sum()))

Users df: 0
Books df: 0
Orders df: 0

In [24]:
print("Users df: "+str(users_df.duplicated(subset=[col for col in users_df.columns if col != 'id']).sum()))
print("Books df: "+str(books_df.duplicated(subset=[col for col in books_df.columns if col != 'id']).sum()))
print("Orders df: "+str(orders_df.duplicated(subset=[col for col in orders_df.columns if col != 'id']).sum()))

Users df: 0
Books df: 0
Orders df: 0

In [3]:
users_df.head(10)

,id,name,address,phone,email
0,53386,Jacqulyn Mante,"566 Emelina Turnpike, Lashundaside, NE 78034-5281",962.715.8009,leonardo.leannon@wintheiser-lueilwitz.example
1,54635,Devon Leannon III,,(537) 133-9394,jon_torp@bayer.example
2,55435,Shiloh Keebler,"425 Wesley Hills, Nathanialburgh, MS 08004",474.242.3397,murray_mcclure@pfeffer.example
3,53627,Luke Rolfson,"Suite 556 20616 Little Union, Connieside, VT 3...",927.381.8818,murray.shanahan@heathcote.example
4,55650,Prince Braun,"981 Howell Spring, New Sheldon, LA 62246-1232",686-186-1306,anitra@pollich-kris.example
5,55698,Pres. Griselda Volkman,"Apt. 552 47051 Marissa Mountains, West Margo, ...",515 978 7734,sharla@hackett.test
6,53320,Willis Spencer,"Apt. 952 20828 Dominick Tunnel, Collenmouth, H...",251.303.0925,ivory@kuvalis-tremblay.example
7,53489,Theressa Wiza,"4436 Karine Shores, O'Connerburgh, OK 32798",306.691.7479,burt_medhurst@damore-koelpin.test
8,55573,Hector Bergstrom,"823 Trent Rue, Fernandotown, CT 35653",970.934.3080,enrique@corkery.example
9,55751,Felipe Blanda,"354 McGlynn Branch, West Martinburgh, OH 32514",737.770.0577,jena@dibbert.example

In [4]:
users_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2810 entries, 0 to 2809
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       2810 non-null   int64
 1   name     2810 non-null   object
 2   address  2713 non-null   object
 3   phone    2810 non-null   object
 4   email    2810 non-null   object
dtypes: int64(1), object(4)
memory usage: 109.9+ KB

In [6]:
books_df.head(10)

,:id,:title,:author,:genre,:publisher,:year
0,21326,Behold the Man,"Trenton Sipes, Clint Hauck VM",Reference book,Bowes & Bowes,1979
1,21546,The Deer Hunter,Norris Gusikowski,Reference book,Koren Publishers Jerusalem,1993
2,21130,Snatch,Rev. Lura Jaskolski,Fable,Left Book Club,2000
3,21287,Dial M for Murder,Miss Elmo Walsh,Textbook,Libertas Academica,1977
4,21237,The Departed,Mario Aufderhar,Folklore,BBC Books,2015
5,21133,That Hideous Strength,Ruby Schowalter,Essay,Brill Publishers,1976
6,21584,A Many-Splendoured Thing,Mohammad Lynch III,Textbook,Hamish Hamilton,1978
7,21269,Led Zeppelin IV,Lawana Veum,Essay,ECW Press,2007
8,21197,Call of Duty: Black Ops III,"Hilario Legros I, Marco Cormier, Adrian Stroma...",Textbook,University of Michigan Press,2013
9,21054,Amadeus,Mrs. Dario Jaskolski,Realistic fiction,Ziff Davis Media,1997

In [7]:
books_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 741 entries, 0 to 740
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   :id         741 non-null    int64
 1   :title      741 non-null    object
 2   :author     741 non-null    object
 3   :genre      741 non-null    object
 4   :publisher  735 non-null    object
 5   :year       739 non-null    object
dtypes: int64(1), object(5)
memory usage: 34.9+ KB

In [8]:
orders_df.head(10)

,id,user_id,book_id,quantity,unit_price,timestamp,shipping
0,75198,55590,21465,1,73.5$,"08:47:31 P.M.,10/07/24",NULL
1,82023,53482,21374,1,$25.00,2024-09-11T05:27:49,NULL
2,81439,55123,21408,1,USD22.50,"2024-08-06,06:53",
3,80259,54387,21013,1,42.5$,03/18/25;09:32:41 AM,
4,80176,54916,21437,1,$ 62.5,"04:55:14 pm,09/24/24",NULL
5,75145,54881,21487,4,$ 73.0,2024-10-16T16:44:45,NULL
6,77748,53943,21283,3,$ 41.75,19.02.2025 06:46:46,"22571 Shena Oval, West Mellissastad, MN 91780"
7,81737,54468,21519,1,46.0 $,"2025-02-01,02:52:35 am",NULL
8,78876,54627,21302,5,22.USD,03/09/25 17:13:59,NULL
9,74442,54189,20936,2,57.00EUR,"11/12/24,16:18",NULL

In [10]:
orders_df.duplicated().sum()

np.int64(0)

In [11]:
orders_df.duplicated(subset=['user_id','book_id','quantity','unit_price','timestamp','shipping']).sum()

np.int64(0)

In [12]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9850 entries, 0 to 9849
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          9850 non-null   int64
 1   user_id     9850 non-null   int64
 2   book_id     9850 non-null   int64
 3   quantity    9850 non-null   int32
 4   unit_price  9850 non-null   object
 5   timestamp   9850 non-null   object
 6   shipping    7467 non-null   object
dtypes: int32(1), int64(3), object(3)
memory usage: 500.3+ KB

In [13]:
pd.DataFrame({
    'empty_string': (books_df == '').sum(),
    'NaN': books_df.isnull().sum(),
    'total_missing': (books_df == '').sum() + books_df.isnull().sum()
})

            empty_string  NaN  total_missing
:id                    0    0              0
:title                 0    0              0
:author                0    0              0
:genre                 0    0              0
:publisher             4    6             10
:year                  1    2              3

In [14]:
pd.DataFrame({
    'empty_string': (users_df == '').sum(),
    'NaN': users_df.isnull().sum(),
    'total_missing': (users_df == '').sum() + users_df.isnull().sum()
})

         empty_string  NaN  total_missing
id                  0    0              0
name                0    0              0
address             0   97             97
phone               0    0              0
email               0    0              0

In [15]:
pd.DataFrame({
    'empty_string': (orders_df == '').sum(),
    'NaN': orders_df.isnull().sum(),
    'total_missing': (orders_df == '').sum() + orders_df.isnull().sum()
})

            empty_string   NaN  total_missing
id                     0     0              0
user_id                0     0              0
book_id                0     0              0
quantity               0     0              0
unit_price             0     0              0
timestamp              0     0              0
shipping            2438  2383           4821