In [14]:
import pandas as pd 
import yaml

users_df = pd.read_csv("../data3/users.csv") 

with open("../data3/books.yaml") as books:
    data=yaml.safe_load(books) 
books_df = pd.DataFrame(data)

orders_df = pd.read_parquet("../data3/orders.parquet")

In [2]:
print("Users df: " + str(users_df.duplicated().sum()))
print("Books df: " + str(books_df.duplicated().sum()))
print("Orders df: " + str(orders_df.duplicated().sum()))

Users df: 0
Books df: 0
Orders df: 0

In [3]:
print("Users df: "+str(users_df.duplicated(subset=[col for col in users_df.columns if col != 'id']).sum()))
print("Books df: "+str(books_df.duplicated(subset=[col for col in books_df.columns if col != 'id']).sum()))
print("Orders df: "+str(orders_df.duplicated(subset=[col for col in orders_df.columns if col != 'id']).sum()))

Users df: 0
Books df: 0
Orders df: 0

In [4]:
users_df.head()

,id,name,address,phone,email
0,47856,Tammie Mayer,"Apt. 371 1875 Gusikowski Stravenue, Moenland, ...",163.212.2656,maire.larson@runolfsdottir-mclaughlin.example
1,49394,Evia Yost,"22610 Mildred Green, Pagacbury, AZ 19393-2103",778.926.6707,byron@johnston.test
2,48386,Margery Gorczany,"Apt. 884 349 Renner Lane, East Darren, NC 30837",992 375 5021,cletus@baumbach.test
3,49547,Edris Kshlerin,"Suite 498 24711 Bechtelar Extensions, Ryanvill...",747.537.2209,leonore@gleason.test
4,50512,Meghan Thiel,"125 Rodger Drive, Rogahnborough, VT 96988-4596",(631) 765-7676,cristine@bayer.test

In [5]:
users_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3466 entries, 0 to 3465
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3466 non-null   int64
 1   name     3466 non-null   object
 2   address  3344 non-null   object
 3   phone    3466 non-null   object
 4   email    3466 non-null   object
dtypes: int64(1), object(4)
memory usage: 135.5+ KB

In [6]:
books_df.head()

,:id,:title,:author,:genre,:publisher,:year
0,21778,Call of Duty: World at War,Elmer Parker,Mythopoeia,Orion Books,2003
1,21374,WarioWare: Touched!,Ms. Kami Prosacco,Mythology,St. Martin's Press,1951
2,21457,Titanic: Music from the Motion Picture,Zoila Christiansen,Historical fiction,"Farrar, Straus & Giroux",2009
3,21881,Flashdance: Original Soundtrack from the Motio...,"Joseph Raynor, Ja Ankunding II",Metafiction,Pen and Sword Books,2024
4,21446,Riot!,Louanne Cruickshank,Mystery,Bellevue Literary Press,1987

In [7]:
books_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 762 entries, 0 to 761
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   :id         762 non-null    int64
 1   :title      762 non-null    object
 2   :author     762 non-null    object
 3   :genre      762 non-null    object
 4   :publisher  759 non-null    object
 5   :year       760 non-null    object
dtypes: int64(1), object(5)
memory usage: 35.8+ KB

In [13]:
orders_df.head(10)

,id,user_id,book_id,quantity,unit_price,timestamp,shipping
0,80941,47864,21550,1,67.0 €,2025-01-11 09:50:11 PM,
1,81245,47864,22052,2,EUR26.99,2024-03-27T07:46:55.055,
2,78477,48918,21367,1,30 $,"11:17:51 PM, 29-JUN-2025",
3,86303,48092,21724,1,18 $,09:29;11/06/24,None
4,81990,48418,21441,1,USD 24.99,2024-09-16;03:05:39 pm,None
5,82785,50265,21459,2,41.50$,2024-06-29T00:13:48.016,
6,84594,49429,21598,1,19.99 $,"6-JUL-2024,15:27",NULL
7,86155,49965,21752,1,61.99 $,"11:28:42 AM, 2025-01-08",
8,82478,50188,21587,1,69.5$,2024-11-08T02:05:08.703,None
9,80811,50433,21899,1,66.99 €,"04:51:52,08/18/24",None

In [9]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8933 entries, 0 to 8932
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          8933 non-null   int64
 1   user_id     8933 non-null   int64
 2   book_id     8933 non-null   int64
 3   quantity    8933 non-null   int32
 4   unit_price  8933 non-null   object
 5   timestamp   8933 non-null   object
 6   shipping    6721 non-null   object
dtypes: int32(1), int64(3), object(3)
memory usage: 453.8+ KB

In [10]:
pd.DataFrame({
    'empty_string': (books_df == '').sum(),
    'NaN': books_df.isnull().sum(),
    'total_missing': (books_df == '').sum() + books_df.isnull().sum()
})

            empty_string  NaN  total_missing
:id                    0    0              0
:title                 0    0              0
:author                0    0              0
:genre                 0    0              0
:publisher             8    3             11
:year                  1    2              3

In [11]:
pd.DataFrame({
    'empty_string': (users_df == '').sum(),
    'NaN': users_df.isnull().sum(),
    'total_missing': (users_df == '').sum() + users_df.isnull().sum()
})

         empty_string  NaN  total_missing
id                  0    0              0
name                0    0              0
address             0  122            122
phone               0    0              0
email               0    0              0

In [12]:
pd.DataFrame({
    'empty_string': (orders_df == '').sum(),
    'NaN': orders_df.isnull().sum(),
    'total_missing': (orders_df == '').sum() + orders_df.isnull().sum()
})

            empty_string   NaN  total_missing
id                     0     0              0
user_id                0     0              0
book_id                0     0              0
quantity               0     0              0
unit_price             0     0              0
timestamp              0     0              0
shipping            2215  2212           4427